# Generated by Django 3.1.5 on 2021-01-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('escuela', models.CharField(max_length=100)),
                ('fecha_de_contratacion', models.DateField()),
                ('sueldo', models.IntegerField()),
            ],
        ),
    ]
