# Generated by Django 3.1.5 on 2021-01-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_de_contratacion', models.DateField()),
                ('sueldo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='asignatura',
            field=models.ManyToManyField(to='app.Asignatura'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('cantidad_de_alumnos', models.IntegerField()),
                ('profesor', models.ManyToManyField(to='app.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('Transportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.transportista')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
            ],
        ),
    ]
